version: "3"

services:
  ################################
  #   Setup postgres container
  ################################
  database:
    image: postgres:11.6
    ports:
        - '5432:5432'
    volumes:
        - ./data/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=movies
      - POSTGRES_USER=movies

  ################################
  #   Setup node container
  ################################
  server:
    build: ./server
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./server/src:/usr/src/server/src/
    command: npm run dev
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=movies
      - POSTGRES_USER=movies

  frontend:
    volumes:
      - ./frontend/src:/usr/src/frontend/src
    command: npm run start
    build: ./frontend
    ports:
      - 3000:3000
    links:
      - server
